name: Dependency review

on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - package-lock.json

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
